Two way ANOVA

In [2]:
#Importing the required library files
import numpy as np 
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [3]:
#Reading our dataset from Preplacementdata.csv
dataset=pd.read_csv("Preplacementdata.csv")

In [4]:
#Checking dataset values to know how it's look like
dataset

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1,67.00,91.00,58.00,55.0,58.80,270000.0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2,79.33,78.33,77.48,86.5,66.28,200000.0,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3,65.00,68.00,64.00,75.0,57.80,250000.0,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4,56.00,52.00,52.00,66.0,59.43,0.0,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5,85.80,73.60,73.30,96.8,55.50,425000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,80.60,82.00,77.60,91.0,74.49,400000.0,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212,58.00,60.00,72.00,74.0,53.62,275000.0,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213,67.00,67.00,73.00,59.0,69.72,295000.0,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,214,74.00,66.00,58.00,70.0,60.23,204000.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,215,62.00,58.00,53.00,89.0,60.22,0.0,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [5]:
#Checking whether our dataset is containing any null values in any of the columns.
dataset.isna().sum()

sl_no             0
ssc_p             0
hsc_p             0
degree_p          0
etest_p           0
mba_p             0
salary            0
gender            0
ssc_b             0
hsc_b             0
hsc_s             0
degree_t          0
workex            0
specialisation    0
status            0
dtype: int64

In [16]:
model = ols('etest_p~gender+ssc_b',data = dataset).fit()

In [17]:
two = sm.stats.anova_lm(model)

In [18]:
two

             df        sum_sq     mean_sq         F    PR(>F)
gender      1.0    267.999364  267.999364  1.517775  0.219321
ssc_b       1.0     16.056355   16.056355  0.090933  0.763290
Residual  212.0  37433.662214  176.573878       NaN       NaN

In [19]:
model1 = ols('etest_p~gender+hsc_b',data = dataset).fit()
three = sm.stats.anova_lm(model1)
three

             df        sum_sq     mean_sq         F    PR(>F)
gender      1.0    267.999364  267.999364  1.518853  0.219158
hsc_b       1.0     42.638857   42.638857  0.241650  0.623525
Residual  212.0  37407.079712  176.448489       NaN       NaN

In [20]:
model2 = ols('etest_p~ssc_b+hsc_b',data = dataset).fit()
four = sm.stats.anova_lm(model2)
four

             df        sum_sq     mean_sq         F    PR(>F)
ssc_b       1.0     13.602921   13.602921  0.076796  0.781957
hsc_b       1.0    152.669444  152.669444  0.861909  0.354261
Residual  212.0  37551.445567  177.129460       NaN       NaN

In [24]:
model3 = ols('etest_p~gender+ssc_b+degree_t',data = dataset).fit()
five = sm.stats.anova_lm(model3)
five

             df        sum_sq     mean_sq         F    PR(>F)
gender      1.0    267.999364  267.999364  1.503859  0.221452
ssc_b       1.0     16.056355   16.056355  0.090099  0.764348
degree_t    2.0     10.041043    5.020522  0.028172  0.972225
Residual  210.0  37423.621171  178.207720       NaN       NaN